stream:
  url: "video/2025-12-28 21-07-39.mp4"  # Local video file path

multi_table:
  auto_detect: false
  max_tables: 4
  layouts:
    - x: 0
      y: 0
      width: 960
      height: 540
    - x: 960
      y: 0
      width: 960
      height: 540
    - x: 0
      y: 540
      width: 960
      height: 540
    - x: 960
      y: 540
      width: 960
      height: 540

roi:
  hero_left:
    x: 380
    y: 420
    width: 70
    height: 95
  hero_right:
    x: 470
    y: 420
    width: 70
    height: 95
  stack:
    x: 370
    y: 500
    width: 180
    height: 30
  dealer_button:
    x: 420
    y: 380
    width: 40
    height: 40

strategy:
  matrix_path: "charts/strategy_matrix.json"
